# Site settings
baseURL = "https://cptranquille2021.netlify.app/"
languageCode = "en-us"
title = "Portfolio Website"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Christopher Tranquille"
  description = "My name is Christopher Tranquille and this is my portfolio website"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [the home page](https://cptranquille2021.netlify.app/)"

  # Navigation Section
  [params.navigation]
    title = "Christopher"
    subtitle = "portfolio website"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "View my work"
      url = "projects"


    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "View my CV"
      url = "cv"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Christopher"
    subtitle = "PORTFOLIO WEBSITE."
    buttonText = "View my work"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
      [[params.tiles.showcase]]
      title = "Biography"
      subtitle = "A short description of my life"
      image = "myface.png"
      url = "projects/biography"

    [[params.tiles.showcase]]
      title = "Climate change and temperature anomalies"
      subtitle = "Data Analysis"
      image = "climate.jpg"
      url = "projects/ccata"
    
      [[params.tiles.showcase]]
      title = "Youth Risk Behavior Surveillance"
      subtitle = "Data Analysis"
      image = "medical-01.jpg"
      url = "projects/yrbss"
    
    [[params.tiles.showcase]]
      title = "Yield Curve inversion"
      subtitle = "Data Analysis"
      image = "stocks.jpg"
      url = "projects/yci"




    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About this website"
    subtitle = "Welcome to my website. This is a website set up for Data Analytics, a course for the Masters of Financial Analysis which I am reading for this year. Thank you for taking a visit!"
    buttonText = "View my work"
    url = "projects"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "c-p-t@hotmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+31 6 5777 3473"

    [[params.contact.address]]
    title = "Crawford Street"
    street = "Marelybone"
    city = "London"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Christopher Tranquille Inc."

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/christopher.tranquille/"
      label = "My Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/chrisstranquille/"
      label = "My Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/cptranquille"
      label = "My GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/ctranquille/"
      label = "My LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
